### ISSUE TITLE
Text Descriptions for Colours

### ISSUE THREAD

**Issue by dzuk-mutant** [mutantstandard/orxporter#1]
Hey, colours need a text description variable that can be put into other variables (ie. text descriptions for actual emoji).

Could you do it in the next 2 weeks? ^^'

(ignore the past edits I am so tired lol)

**Comment by kiilas** [comment]
done, do you also want --force-desc so it complains when emoji has a missing desc?

**Comment by kiilas** [comment]
--force-desc done
