### ISSUE TITLE
Automatically determine root if emoji isn't modifiable

### ISSUE THREAD

**Issue by dzuk-mutant** [mutantstandard/orxporter#2]
(Making the issue as previously discussed in private chat, just explaining it for the public)

Instead of having to explicitly define `root` for every emoji, only emoji that can be modified should need an explicitly-defined `root`. For any other emoji, it should just infer the root from `code`.

This is because modifiable emoji are very few in number and it results in a lot of redundant duplicate data entries for all the others.

Could this be done in the next week?

**Comment by kiilas** [comment]
done
