### ISSUE TITLE
Switch rasteriser from Inkscape to resvg

### ISSUE THREAD

**Issue by dzuk-mutant** [mutantstandard/orxporter#4]
resvg (https://github.com/RazrFalcon/resvg) is a much more efficient SVG renderer that's been benchmarked as 10x faster than Inkscape in a particular test with an icon suite. It also has a CLI application (https://github.com/RazrFalcon/resvg/tree/master/tools/rendersvg - like Inkscape is for our purposes) but it also has a C and Rust library if those are possibly more useful.

It doesn't support all SVG attributes, but the ones it doesn't support are ones this project doesnt have a need for (like animation and filters).

I would really like this in Orxporter as soon as possible because it seems like it would make raster build times trivial again on my hardware.

**Comment by kiilas** [comment]
done
