### ISSUE TITLE
Output to fonts (forc integration)

### ISSUE THREAD

**Issue by dzuk-mutant** [mutantstandard/orxporter#6]
Compiling the emoji declared by the manifests that have unicode codepoints into a font format.

# Formats
There is not one single emoji format, and not one single emoji format has a monopoly or widespread support.

There are 3 major font formats we should support, with a 4th as a stretch if it's easy enough to encode. These are in order of importance and how easy they probably are to implement:

### SVGinOT (Mozilla, Adobe, Open Source)
SVGinOT is simple embedding of SVG data.

Supported in certain linux distros, as well as in Firefox as of Version 50.
Supported by Windows 10 and/or Microsoft Edge in some way. (I can't remember exactly.)

### sbix (Apple)
Embedding raster images (ie. PNG) at different 'strikes' (resolutions) that are automatically selected based on things like font size and DPI.

I need to do some more research to find out how these strikes are implemented.

At the current time of writing, Apple platforms only support sbix at a system level.

### CBDT/CBLC (Google)
Another raster format that uses PNGs (sbix has different raster format options, this only uses PNG). Google has open source code where they have successfully compiled SVG images into a font of this format.

Used by Android and Chrome OS at a system level.
Supported by Windows 10 and/or Microsoft Edge in some way. (I can't remember exactly.)

### COLR/CPAL (stretch) (Microsoft, but is possibly being phased out)
Different layers of vector graphical information are overlaid on top of each other and given colour palettes. It's a weird one and I'd need to learn more information about it.

Used by Windows 8 and 10, but IIRC, Microsoft is phasing this out in Windows 10 favour of one of the other vector formats, and Windows 10 has certain degrees of support for the other vector formats anyway. But that leaves out Windows 8, which only supports CPAL.

# Building and manifests

suggested usage in build command line:

```
-F svg,png-32,png-128,png-512,svginot,sbix-32-64-128,cbdtcblc-32-64-128,colrcpal

```
(sbix and CBDT/CBLC resolutions might be a bit more complicated than this, but that's my current understanding)

suggested ouput structure (using the above build command segment)

```
/out
- /svg
- /png-32
- /png-128
- /png-512
- sbix.ttc
- svginot.otf
- cbdtcblc.ttf
- colrcpal.ttf

(can't remember the exact required file extensions, just take this as a hypothetical)
```
There should also be additional information for the manifests regarding font properties and especially font metadata. Some of these should not be optional because they will not be considered valid in some or all operating systems if they are not entered. I've worked out some of them, I need to work out more of them.

```
font

  family = Mutant Standard emoji
  subfamily = Regular

  typographic_family =  Mutant Standard emoji
  typographic_subfamily = Regular

[...]
```

# Creating a new library to provide this functionality

As per our private conversation about it, it's probably best that a new library be created that can facilitate these functionalities, which orxporter then invokes. This is so other people who don't want to use orxporter's build methods can still benefit from being able to use this emoji font output tool, as the options that exist out there that are this comprehensive and functional are basically nonexistent.

Either orxporter or this library will need to determine some metadata in advance that shouldn't be edited by users and refuse to build if certain parameters or metadata entries are not properly set. (I'm working out what those are and can come back with them in this issue thing I guess?)

**Comment by s5bug** [comment]
I was working on [scolor](https://gitlab.com/srnb/scolor) for this but I lost the motivation for it due to having to wade through the CFF2 docs with little understanding of how they worked. I'll pick it back up when I find sufficient time to and see if I can finally get it in a working state.

**Comment by dzuk-mutant** [comment]
This has been closed since forc is now designed to compliment orxporter in a way that doesn't require orxporter to do anything special.
